language: java
jdk:
- openjdk8
script: mvn clean verify

deploy:
  on:
    branch: develop
  provider: heroku
  api_key:
    secure: JBP6YAxori2e9jKTxzlyBGZJmjYF+XrFaEONDRnLmF+oN08SFyjgaM96tQRZUSwq9mXEszq7QLO89fkO08OBMWzGRt3vP043HbsNizUA0sgDbOCh77dJu2yzYjJA3BvT2G9Ay6s1lkDkVI7eTF1X8niUvW1nHP8qQ9v9zIG9f+kk65IzsUqv2mGWFaO2DEcSJu15cOTZV3m3PTZM2G7f48rQGQk0t3QPfUxteFVaF3VyKH8ZyoFiHInAhJKSkVyv0DjH2kYSrHjjtEfS9ps8L6ZQfZT3i5LAtaKaESbiyp/uj1kQFlRrj9iq7W9nyPO7PH9sdUOCVKfdnxIQ11GYoM+2G9WgD7X2y/w0TZD0rU4/XjvMCeceWgEH2kLAolWtsltU1tdYdL+vTMBG8uY5zxCDlzmO9qubVLua4NouZap/L5bkVCm+vAlcIrjxeG3MGiFgJqddy9grcbTLKlflgPNEhxTd5QEwI4hS3l581Q1eJV56eSQEeXRooXCGz9bj9MHLskdF6jlpSKMjX22yLpMaPVWvSdUHi2vzUGooi2fpDzSyfC8ZST9qT0avEEC2/tBP5URSpc0z1NH2SvowBa2zstiVZGndd1XHQhtpU08ClEeiE1he0tO0n3X1Q7BV9AkXt0Fb+2Etc9kx3U73Sg+4twjX/ZHAcZEcfGFhfN8=
  app: saheed-lasisi-skeleton
